import { defineOverlay } from "@/sdk/overlay";

// Ayarların çoğu Pedallar & Girdi (inputs) ile aynı anahtarları kullanır: ortak model (inputs/shared.tsx) onları okur
// ve eski kopyalar buraya taşınırken (settings.ts → inputsPedalsMigrate) değerler olduğu gibi aktarılır.
export default defineOverlay({
  id: "pedals",
  name: "Pedal Seti",
  description: "Grafiksiz pedal göstergesi: gaz / fren / debriyaj pedalları, yüzdeler, vites, hız ve direksiyon; isteğe bağlı son / en iyi tur satırı. Yedi tasarım.",
  category: "driving",
  // Tekrar ekranında çalışmaz (sürüş verisi yalnızca kendin sürerken gelir)
  replay: false,
  topics: [{ name: "inputs", hz: 60 }],
  size: { w: 300, h: 130 },
  defaultPosition: { x: 420, y: 900 },
  defaultEnabled: false,
  resize: { w: "width", wMin: true },
  settings: [
    {
      key: "design",
      label: "Tasarım",
      type: "select",
      default: "bars",
      options: [
        { value: "pedals", label: "Pedal seti", pro: true },
        { value: "bars", label: "Dikey çubuklar" },
        { value: "strip", label: "Kompakt şerit" },
        { value: "horizontal", label: "Yatay şeritler", pro: true },
        { value: "rings", label: "Halka göstergeler", pro: true },
        { value: "segments", label: "LED segmentler" },
        { value: "hud", label: "HUD (çerçevesiz)", pro: true },
      ],
      hint: "Pedal göstergesinin genel görünümü. Renkler, ABS / TC, debriyaj, direksiyon ve vites ayarları bütün tasarımlarda geçerlidir. Pedal izi grafiği için Pedallar & Girdi overlay'ini kullan.",
      proHint: "Yatay şeritler, halka göstergeler ve HUD tasarımları PRO üyelere özel.",
    },
    {
      key: "showPct",
      label: "Gaz / fren yüzdesini göster",
      type: "boolean",
      default: true,
      hint: "Gaz ve fren (açıksa debriyaj) göstergelerinin yanında pedala ne kadar basıldığını yüzde olarak yazar.",
    },
    {
      key: "barWidth",
      label: "Çubuk kalınlığı",
      type: "number",
      default: 12,
      min: 6,
      max: 24,
      step: 1,
      unit: "px",
      showIf: { key: "design", not: ["pedals"] },
    },
    { key: "width", label: "Genişlik (en az)", type: "number", default: 100, min: 100, max: 1000, step: 10, unit: "px", hint: "Gösterge en az bu genişlikte olur; içerik sığmıyorsa kendiliğinden genişler. Düzenleme modunda pencerenin sağ / sol kenarından sürükleyerek de ayarlanır." },
    { key: "showClutch", label: "Debriyaj", type: "boolean", default: false },
    { key: "showSteer", label: "Direksiyon", type: "boolean", default: true },
    {
      key: "wheelStyle",
      label: "Direksiyon görünümü",
      type: "select",
      default: "auto",
      group: "Direksiyon",
      showIf: { key: "showSteer", is: [true] },
      options: [
        { value: "auto", label: "Otomatik (araca göre)" },
        { value: "device", label: "Otomatik (bağlı direksiyona göre)" },
        { value: "round", label: "Yuvarlak" },
        { value: "formula", label: "Formula", pro: true },
        { value: "gt", label: "GT", pro: true },
        { value: "proto", label: "Dayanıklılık / Prototip", pro: true },
        { value: "rally", label: "Ralli", pro: true },
        { value: "oval", label: "Oval / Stock car", pro: true },
        { value: "classic", label: "Klasik (ahşap)", pro: true },
        { value: "truck", label: "Kamyon / otobüs", pro: true },
      ],
      hint: "Araca göre: sürdüğün araca (formula, GT, prototip, ralli, oval) uygun direksiyonu seçer. Bağlı direksiyona göre: bilgisayara takılı direksiyonu tanır ve türüne (yuvarlak, GT, formula, kamyon) uyan çizimi gösterir; ürünün fotoğrafı değil, o türün genel çizimidir. Direksiyon tanınamazsa araca göre seçilir.",
      proHint: "Tasarımlı direksiyonlar PRO üyelere özel; otomatik modda sana yuvarlak direksiyon gösterilir.",
    },
    {
      key: "wheelSize",
      label: "Direksiyon boyutu",
      type: "number",
      default: 100,
      min: 80,
      max: 150,
      step: 5,
      unit: "%",
      group: "Direksiyon",
      showIf: { key: "showSteer", is: [true] },
    },
    {
      key: "wheelAccentOn",
      label: "Özel vurgu rengi",
      type: "boolean",
      default: false,
      group: "Direksiyon",
      showIf: { key: "showSteer", is: [true] },
      hint: "Kapalıyken temanın vurgu rengi kullanılır.",
    },
    {
      key: "wheelAccent",
      label: "Vurgu rengi",
      type: "color",
      default: "#ff8a2a",
      group: "Direksiyon",
      showIf: { key: "wheelAccentOn", is: [true] },
    },
    {
      key: "showSteerDeg",
      label: "Direksiyon açısını göster (°)",
      type: "boolean",
      default: false,
      group: "Direksiyon",
      showIf: { key: "showSteer", is: [true] },
    },
    { key: "showGear", label: "Vites ve hız", type: "boolean", default: true },
    {
      key: "showLastLap",
      label: "Son tur süresi satırı",
      type: "boolean",
      default: false,
      group: "Tur süreleri",
      hint: "Göstergenin altına son turunun süresini yazan bir satır ekler.",
    },
    { key: "showBestLap", label: "En iyi tur süresi satırı", type: "boolean", default: false, group: "Tur süreleri" },
    { key: "throttleColor", label: "Gaz rengi", type: "color", default: "#33d17a" },
    { key: "brakeColor", label: "Fren rengi", type: "color", default: "#ff4d4f" },
    {
      key: "absMode",
      label: "ABS göstergesi",
      type: "select",
      default: "both",
      group: "ABS / TC",
      options: [
        { value: "bar", label: "Bar rengi" },
        { value: "frame", label: "Dış çerçeve" },
        { value: "both", label: "İkisi" },
        { value: "off", label: "Kapalı" },
      ],
      hint: "ABS çalışırken fren göstergesi bu renge döner ya da çubuğun dışında renkli bir çerçeve yanar. Sim ABS bilgisini vermiyorsa değişmez.",
    },
    {
      key: "absColor",
      label: "ABS çalışınca fren rengi",
      type: "color",
      default: "#ffd400",
      group: "ABS / TC",
      showIf: { key: "absMode", not: ["off"] },
    },
    {
      key: "tcMode",
      label: "TC göstergesi",
      type: "select",
      default: "both",
      group: "ABS / TC",
      options: [
        { value: "bar", label: "Bar rengi" },
        { value: "frame", label: "Dış çerçeve" },
        { value: "both", label: "İkisi" },
        { value: "off", label: "Kapalı" },
      ],
      hint: "Çekiş kontrolü gazı keserken gaz göstergesi bu renge döner. Şimdilik ACC ve AC bu bilgiyi veriyor.",
    },
    {
      key: "tcColor",
      label: "TC çalışınca gaz rengi",
      type: "color",
      default: "#00c8ff",
      group: "ABS / TC",
      showIf: { key: "tcMode", not: ["off"] },
    },
    { key: "hz", label: "Güncelleme sıklığı", type: "number", default: 60, min: 20, max: 60, step: 10, unit: "Hz" },
  ],
});
