import { defineOverlay } from "@/sdk/overlay";

export default defineOverlay({
  id: "setupcover",
  name: "Setup Örtüsü",
  description:
    "Garajda araç ayarlarını (setup) yaparken yayında o bölgeyi örter: izleyiciler ve rakipler ayar değerlerini göremez. Piste çıkınca kendiliğinden kaybolur. Logo, yazı ve renkler ayarlanabilir.",
  category: "stream",
  noBgOpacity: true,
  topics: [{ name: "status", hz: 2 }],
  size: { w: 1024, h: 768 },
  defaultPosition: { x: 448, y: 156 },
  defaultEnabled: false,
  defaultAlwaysShow: true,
  multiInstance: true,
  resize: false,
  settings: [
    {
      key: "when",
      label: "Ne zaman görünsün",
      type: "select",
      default: "menu",
      options: [
        { value: "menu", label: "Garaj / setup ekranı açıkken" },
        { value: "offtrack", label: "Pistte değilken (garaj + pit menüsü)" },
        { value: "garage", label: "Yalnızca garajdayken" },
        { value: "always", label: "Her zaman" },
      ],
      hint: "İlk seçenek garaj ekranının açık olduğunu bildiren simlerde (iRacing) yalnızca o ekran açıkken örter; diğer simlerde pistte değilken örter. Yayında görünmesi için OBS'e SRTR Pitwall tarayıcı kaynağını eklemiş olmalısın.",
    },
    { key: "w", label: "Genişlik", type: "number", default: 1024, min: 200, max: 3840, step: 10, unit: "px", group: "Boyut" },
    { key: "h", label: "Yükseklik", type: "number", default: 768, min: 120, max: 2160, step: 10, unit: "px", group: "Boyut", hint: "Tasarımı ve görseli değiştirmek yayın logosu izni olan PRO üyelere açıktır; diğerlerinde SRTR Pitwall görseli gösterilir." },
    {
      key: "design",
      label: "Tasarım",
      type: "select",
      default: "banner",
      group: "İçerik",
      logoPerm: true,
      options: [
        { value: "banner", label: "Görsel tüm alanı kaplar" },
        { value: "logo", label: "Ortada logo ve yazı" },
      ],
    },
    { key: "logo", logoPerm: true, label: "Görsel / logo", type: "image", default: "", maxSize: 1920, group: "İçerik", hint: "Boşsa SRTR Pitwall görseli gösterilir (pitwall.simracetr.com adresiyle)" },
    { key: "showLogo", logoPerm: true, label: "Logoyu göster", type: "boolean", default: true, group: "İçerik", showIf: { key: "design", is: ["logo"] } },
    { key: "logoSize", logoPerm: true, label: "Logo boyutu", type: "number", default: 220, min: 40, max: 800, step: 10, unit: "px", group: "İçerik", showIf: { key: "design", is: ["logo"] } },
    { key: "title", logoPerm: true, label: "Başlık", type: "text", default: "", placeholder: "Setup gizli", group: "İçerik", showIf: { key: "design", is: ["logo"] } },
    { key: "subtitle", logoPerm: true, label: "Alt yazı", type: "text", default: "", placeholder: "Ayarlar yapılıyor, birazdan pistteyiz", group: "İçerik", showIf: { key: "design", is: ["logo"] } },
    { key: "showText", logoPerm: true, label: "Yazıları göster", type: "boolean", default: true, group: "İçerik", showIf: { key: "design", is: ["logo"] } },
    { key: "bg", logoPerm: true, label: "Arka plan rengi", type: "color", default: "#0d0f14", group: "Görünüm" },
    { key: "accent", label: "Vurgu rengi", type: "color", default: "#ff8a2a", group: "Görünüm" },
    { key: "text", logoPerm: true, label: "Yazı rengi", type: "color", default: "#f2f4f8", group: "Görünüm" },
    { key: "stripes", logoPerm: true, label: "Şerit deseni", type: "boolean", default: true, group: "Görünüm", showIf: { key: "design", is: ["logo"] } },
    { key: "frame", label: "Çerçeve", type: "boolean", default: true, group: "Görünüm" },
    { key: "radius", label: "Köşe yuvarlaklığı", type: "number", default: 14, min: 0, max: 80, step: 1, unit: "px", group: "Görünüm" },
    { key: "fade", label: "Yumuşak geçiş", type: "boolean", default: true, group: "Görünüm" },
  ],
});
