; SRTR Pitwall kurulum metinleri (Finnish). Tauri 2.12.0 yerleşik dil dosyasıyla aynı anahtarlar + srtrWelcomeText.
; Kodlama: BOM'suz UTF-8 (Tauri derlerken BOM'u kendisi ekler; BOM'lu kaydetmeyin).
LangString addOrReinstall ${LANG_FINNISH} "Lisää/asenna osat uudelleen"
LangString alreadyInstalled ${LANG_FINNISH} "Jo asennettu"
LangString alreadyInstalledLong ${LANG_FINNISH} "${PRODUCTNAME} ${VERSION} on jo asennettu. Valitse suoritettava toiminto ja jatka valitsemalla Seuraava."
LangString appRunning ${LANG_FINNISH} "${PRODUCTNAME} on käynnissä! Sulje se ensin ja yritä uudelleen."
LangString appRunningOkKill ${LANG_FINNISH} "${PRODUCTNAME} on käynnissä!$\nSulje se valitsemalla OK"
LangString chooseMaintenanceOption ${LANG_FINNISH} "Valitse suoritettava ylläpitotoiminto."
LangString choowHowToInstall ${LANG_FINNISH} "Valitse, miten haluat asentaa sovelluksen ${PRODUCTNAME}."
LangString createDesktop ${LANG_FINNISH} "Luo pikakuvake työpöydälle"
LangString dontUninstall ${LANG_FINNISH} "Älä poista asennusta"
LangString dontUninstallDowngrade ${LANG_FINNISH} "Älä poista asennusta (vanhempaan versioon siirtyminen ilman asennuksen poistoa on poistettu käytöstä tässä asennusohjelmassa)"
LangString failedToKillApp ${LANG_FINNISH} "Sovelluksen ${PRODUCTNAME} sulkeminen epäonnistui. Sulje se ensin ja yritä uudelleen"
LangString installingWebview2 ${LANG_FINNISH} "Asennetaan WebView2..."
LangString newerVersionInstalled ${LANG_FINNISH} "Sovelluksen ${PRODUCTNAME} uudempi versio on jo asennettu! Vanhemman version asentamista ei suositella. Jos haluat todella asentaa tämän vanhemman version, nykyinen versio kannattaa poistaa ensin. Valitse suoritettava toiminto ja jatka valitsemalla Seuraava."
LangString older ${LANG_FINNISH} "vanhempi"
LangString olderOrUnknownVersionInstalled ${LANG_FINNISH} "Järjestelmään on asennettu sovelluksen ${PRODUCTNAME} versio ($R4). On suositeltavaa poistaa nykyinen versio ennen asennusta. Valitse suoritettava toiminto ja jatka valitsemalla Seuraava."
LangString silentDowngrades ${LANG_FINNISH} "Vanhempaan versioon siirtyminen on poistettu käytöstä tässä asennusohjelmassa, joten hiljaista asennusta ei voi jatkaa. Käytä graafista asennusohjelmaa.$\n"
LangString unableToUninstall ${LANG_FINNISH} "Asennuksen poisto epäonnistui!"
LangString uninstallApp ${LANG_FINNISH} "Poista ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_FINNISH} "Poista asennus ennen asentamista"
LangString unknown ${LANG_FINNISH} "tuntematon"
LangString webview2AbortError ${LANG_FINNISH} "WebView2:n asennus epäonnistui! Sovellus ei toimi ilman sitä. Yritä käynnistää asennusohjelma uudelleen."
LangString webview2DownloadError ${LANG_FINNISH} "Virhe: WebView2:n lataus epäonnistui - $0"
LangString webview2DownloadSuccess ${LANG_FINNISH} "WebView2-käynnistysohjelma ladattu"
LangString webview2Downloading ${LANG_FINNISH} "Ladataan WebView2-käynnistysohjelmaa..."
LangString webview2InstallError ${LANG_FINNISH} "Virhe: WebView2:n asennus epäonnistui, lopetuskoodi $1"
LangString webview2InstallSuccess ${LANG_FINNISH} "WebView2 asennettu"
LangString deleteAppData ${LANG_FINNISH} "Poista sovelluksen tiedot"
LangString srtrWelcomeText ${LANG_FINNISH} "SRTR Pitwall on overlay-kokoelma simulaattoriajoon: relative, tilanne, polttoaine, ratakartta, mittaristot, ääni-insinööri ja paljon muuta. Toimii seuraavien kanssa: iRacing, Assetto Corsa Competizione, Assetto Corsa, Le Mans Ultimate / rFactor 2 ja Automobilista 2."
