import { defineOverlay } from "@/sdk/overlay";

export default defineOverlay({
  id: "inputs",
  name: "Pedallar & Girdi",
  description: "Gaz/fren/debriyaj izi, anlık pedal çubukları ve yüzdeleri, vites, hız, direksiyon; isteğe bağlı son / en iyi tur satırı. On iki tasarım.",
  category: "driving",
  topics: [{ name: "inputs", hz: 60 }],
  size: { w: 420, h: 110 },
  defaultPosition: { x: 750, y: 920 },
  defaultEnabled: true,
  settings: [
    {
      key: "design",
      label: "Tasarım",
      type: "select",
      default: "default",
      options: [
        { value: "default", label: "Varsayılan" },
        { value: "trace", label: "Telemetri grafiği + çubuklar" },
        { value: "bars", label: "Dikey çubuklar" },
        { value: "strip", label: "Kompakt şerit" },
        { value: "horizontal", label: "Yatay şeritler", pro: true },
        { value: "rings", label: "Halka göstergeler", pro: true },
        { value: "sim", label: "Sim tarzı (klasik)", pro: true },
        { value: "segments", label: "LED segmentler" },
        { value: "tower", label: "Dikey kule" },
        { value: "wide", label: "Geniş grafik" },
        { value: "pedals", label: "Pedal seti", pro: true },
        { value: "hud", label: "HUD (çerçevesiz)", pro: true },
      ],
      hint: "Pedal ve girdi göstergesinin genel görünümü. Renkler, ABS / TC, debriyaj, direksiyon ve vites ayarları bütün tasarımlarda geçerlidir.",
      proHint: "Yatay şeritler, halka göstergeler, sim tarzı, pedal seti ve HUD tasarımları PRO üyelere özel.",
    },
    {
      key: "showPct",
      label: "Gaz / fren yüzdesini göster",
      type: "boolean",
      default: true,
      hint: "Gaz ve fren (açıksa debriyaj) göstergelerinin yanında pedala ne kadar basıldığını yüzde olarak yazar.",
    },
    {
      key: "barWidth",
      label: "Çubuk kalınlığı",
      type: "number",
      default: 12,
      min: 6,
      max: 24,
      step: 1,
      unit: "px",
      showIf: { key: "design", is: ["trace", "bars", "strip", "horizontal", "rings", "sim", "segments", "tower", "wide", "hud"] },
    },
    {
      key: "steerLine",
      label: "Grafikte direksiyon çizgisi",
      type: "boolean",
      default: false,
      showIf: { key: "design", is: ["trace", "sim", "wide"] },
      hint: "Pedal izinin üstüne direksiyon açısını ince bir çizgiyle ekler (orta = düz). Direksiyon açıkken çizilir.",
    },
    { key: "seconds", label: "İz süresi", type: "number", default: 6, min: 2, max: 15, step: 1, unit: "sn" },
    { key: "showTrace", label: "Pedal izi grafiği", type: "boolean", default: true, showIf: { key: "design", not: ["bars", "strip", "horizontal", "rings", "segments", "tower", "wide", "pedals", "hud"] } },
    {
      key: "smooth",
      label: "Yumuşak grafik",
      type: "boolean",
      default: false,
      hint: "Pedal izini köşeli çizgiler yerine yumuşak eğrilerle çizer.",
    },
    { key: "showClutch", label: "Debriyaj", type: "boolean", default: false },
    { key: "showSteer", label: "Direksiyon", type: "boolean", default: true },
    {
      key: "wheelStyle",
      label: "Direksiyon görünümü",
      type: "select",
      default: "auto",
      group: "Direksiyon",
      showIf: { key: "showSteer", is: [true] },
      options: [
        { value: "auto", label: "Otomatik (araca göre)" },
        { value: "device", label: "Otomatik (bağlı direksiyona göre)" },
        { value: "round", label: "Yuvarlak" },
        { value: "formula", label: "Formula", pro: true },
        { value: "gt", label: "GT", pro: true },
        { value: "proto", label: "Dayanıklılık / Prototip", pro: true },
        { value: "rally", label: "Ralli", pro: true },
        { value: "oval", label: "Oval / Stock car", pro: true },
        { value: "classic", label: "Klasik (ahşap)", pro: true },
        { value: "truck", label: "Kamyon / otobüs", pro: true },
      ],
      hint: "Araca göre: sürdüğün araca (formula, GT, prototip, ralli, oval) uygun direksiyonu seçer. Bağlı direksiyona göre: bilgisayara takılı direksiyonu tanır ve türüne (yuvarlak, GT, formula, kamyon) uyan çizimi gösterir; ürünün fotoğrafı değil, o türün genel çizimidir. Direksiyon tanınamazsa araca göre seçilir.",
      proHint: "Tasarımlı direksiyonlar PRO üyelere özel; otomatik modda sana yuvarlak direksiyon gösterilir.",
    },
    {
      key: "wheelSize",
      label: "Direksiyon boyutu",
      type: "number",
      default: 100,
      min: 80,
      max: 150,
      step: 5,
      unit: "%",
      group: "Direksiyon",
      showIf: { key: "showSteer", is: [true] },
    },
    {
      key: "wheelAccentOn",
      label: "Özel vurgu rengi",
      type: "boolean",
      default: false,
      group: "Direksiyon",
      showIf: { key: "showSteer", is: [true] },
      hint: "Kapalıyken temanın vurgu rengi kullanılır.",
    },
    {
      key: "wheelAccent",
      label: "Vurgu rengi",
      type: "color",
      default: "#ff8a2a",
      group: "Direksiyon",
      showIf: { key: "wheelAccentOn", is: [true] },
    },
    {
      key: "showSteerDeg",
      label: "Direksiyon açısını göster (°)",
      type: "boolean",
      default: false,
      group: "Direksiyon",
      showIf: { key: "showSteer", is: [true] },
    },
    { key: "showGear", label: "Vites ve hız", type: "boolean", default: true },
    {
      key: "showLastLap",
      label: "Son tur süresi satırı",
      type: "boolean",
      default: false,
      group: "Tur süreleri",
      hint: "Göstergenin altına son turunun süresini yazan bir satır ekler.",
    },
    { key: "showBestLap", label: "En iyi tur süresi satırı", type: "boolean", default: false, group: "Tur süreleri" },
    { key: "throttleColor", label: "Gaz rengi", type: "color", default: "#33d17a" },
    { key: "brakeColor", label: "Fren rengi", type: "color", default: "#ff4d4f" },
    {
      key: "absMode",
      label: "ABS göstergesi",
      type: "select",
      default: "both",
      group: "ABS / TC",
      options: [
        { value: "bar", label: "Bar rengi" },
        { value: "frame", label: "Dış çerçeve" },
        { value: "both", label: "İkisi" },
        { value: "off", label: "Kapalı" },
      ],
      hint: "ABS çalışırken fren çubuğu ve pedal izi bu renge döner ya da çubuğun dışında renkli bir çerçeve yanar. Sim ABS bilgisini vermiyorsa değişmez.",
    },
    {
      key: "absColor",
      label: "ABS çalışınca fren rengi",
      type: "color",
      default: "#ffd400",
      group: "ABS / TC",
      showIf: { key: "absMode", not: ["off"] },
    },
    {
      key: "tcMode",
      label: "TC göstergesi",
      type: "select",
      default: "both",
      group: "ABS / TC",
      options: [
        { value: "bar", label: "Bar rengi" },
        { value: "frame", label: "Dış çerçeve" },
        { value: "both", label: "İkisi" },
        { value: "off", label: "Kapalı" },
      ],
      hint: "Çekiş kontrolü gazı keserken gaz çubuğu ve izi bu renge döner. Şimdilik ACC ve AC bu bilgiyi veriyor.",
    },
    {
      key: "tcColor",
      label: "TC çalışınca gaz rengi",
      type: "color",
      default: "#00c8ff",
      group: "ABS / TC",
      showIf: { key: "tcMode", not: ["off"] },
    },
    { key: "hz", label: "Güncelleme sıklığı", type: "number", default: 60, min: 20, max: 60, step: 10, unit: "Hz" },
  ],
});
