import { defineOverlay } from "@/sdk/overlay";

export default defineOverlay({
  id: "incidents",
  name: "Olay Sayacı",
  description: "Tamamlanan tur ve olay puanın; yarışın olay sınırına yaklaştıkça renk değiştiren çubuk. Dört görünüm, renkler ve eşikler ayarlanabilir.",
  category: "info",
  topics: [{ name: "session", hz: 2 }],
  size: { w: 190, h: 230 },
  defaultPosition: { x: 1720, y: 60 },
  defaultEnabled: false,
  settings: [
    {
      key: "design",
      label: "Görünüm",
      type: "select",
      default: "classic",
      options: [
        { value: "classic", label: "Kutular" },
        { value: "compact", label: "Tek satır" },
        { value: "ring", label: "Halka" },
        { value: "segments", label: "Bölmeli çubuk" },
      ],
    },
    {
      key: "layout",
      label: "Yerleşim",
      type: "select",
      default: "stack",
      options: [
        { value: "stack", label: "Alt alta" },
        { value: "row", label: "Yan yana" },
      ],
    },
    { key: "showLaps", label: "Tur", type: "boolean", default: true },
    { key: "showLimit", label: "Sınırı göster", type: "boolean", default: true, hint: "Olay sayısının yanında yarışın olay sınırını da yazar (ör. 4/17x)." },
    { key: "showLeft", label: "Kalan hakkı göster", type: "boolean", default: false },
    { key: "showBar", label: "Çubuğu göster", type: "boolean", default: true, showIf: { key: "design", is: ["classic", "compact", "segments"] } },
    { key: "width", label: "Genişlik", type: "number", default: 100, min: 60, max: 250, step: 5, unit: "%", group: "Biçim" },
    { key: "barH", label: "Çubuk kalınlığı", type: "number", default: 5, min: 2, max: 20, step: 1, unit: "px", group: "Biçim" },
    { key: "radius", label: "Köşe yuvarlaklığı", type: "number", default: -1, min: -1, max: 40, step: 1, unit: "px", group: "Biçim", hint: "-1: temanın köşe yuvarlaklığı kullanılır." },
    { key: "warnAt", label: "Sarı eşiği", type: "number", default: 50, min: 5, max: 95, step: 5, unit: "%", group: "Renkler", hint: "Olay sayısı sınırın bu oranına ulaşınca renk değişir." },
    { key: "dangerAt", label: "Kırmızı eşiği", type: "number", default: 80, min: 10, max: 100, step: 5, unit: "%", group: "Renkler" },
    { key: "blink", label: "Kırmızıdayken yanıp sönsün", type: "boolean", default: false, group: "Renkler" },
    { key: "customColors", label: "Özel renkler", type: "boolean", default: false, group: "Renkler", hint: "Kapalıyken temanın (ya da bu overlay'in Görünüm ayarının) renkleri kullanılır." },
    { key: "safeColor", label: "Güvenli rengi", type: "color", default: "#3ddc84", group: "Renkler", showIf: { key: "customColors", is: [true] } },
    { key: "warnColor", label: "Uyarı rengi", type: "color", default: "#ffd23f", group: "Renkler", showIf: { key: "customColors", is: [true] } },
    { key: "dangerColor", label: "Tehlike rengi", type: "color", default: "#ff4d4d", group: "Renkler", showIf: { key: "customColors", is: [true] } },
    { key: "bg", label: "Arka plan rengi", type: "color", default: "#0c0e13", group: "Renkler", showIf: { key: "customColors", is: [true] } },
    { key: "bgAlpha", label: "Arka plan opaklığı", type: "number", default: 86, min: 0, max: 100, step: 5, unit: "%", group: "Renkler", showIf: { key: "customColors", is: [true] } },
    { key: "valueColor", label: "Değer rengi", type: "color", default: "#f2f4f8", group: "Renkler", showIf: { key: "customColors", is: [true] } },
    { key: "titleColor", label: "Başlık ve birim rengi", type: "color", default: "#9aa3b2", group: "Renkler", showIf: { key: "customColors", is: [true] } },
    { key: "borderColor", label: "Kenarlık rengi", type: "color", default: "#2a2f3a", group: "Renkler", showIf: { key: "customColors", is: [true] } },
    {
      key: "fallbackLimit",
      label: "Sınır yoksa varsayılan",
      type: "number",
      default: 17,
      min: 0,
      max: 60,
      step: 1,
      unit: "x",
      hint: "Oturumda olay sınırı tanımlı değilse çubuk bu değere göre dolar (0 = çubuk yok).",
    },
  ],
});
