import { defineOverlay } from "@/sdk/overlay";

const PRO_HINT = "Düz çubuk herkese açık; diğer görünümler PRO'ya özel.";

export default defineOverlay({
  id: "spotterbar",
  name: "Çubuk Spotter",
  description:
    "Ekranın iki yanında ince birer çubuk: sadece solunda ya da sağında araç varken o taraftaki çubuk yanar, işaret aracın arkadan öne ilerleyişini gösterir.",
  category: "driving",
  topics: [
    { name: "radar", hz: 30 },
    { name: "inputs", hz: 5 },
  ],
  // Varsayılan ayarlarla: 600 boşluk + 2 × 24 çubuk, 180 yükseklik
  size: { w: 648, h: 180 },
  // 1920×1080 ekranın tam ortası; eklenirken hedef monitörün ortasına alınır (defaultCenter)
  defaultPosition: { x: 636, y: 450 },
  defaultCenter: true,
  defaultEnabled: false,
  settings: [
    {
      key: "design",
      label: "Görünüm",
      type: "select",
      default: "flat",
      proHint: PRO_HINT,
      options: [
        { value: "flat", label: "Düz çubuk" },
        { value: "arc", label: "Yay (uçları soluk)", pro: true },
        { value: "fade", label: "Soluk uçlu", pro: true },
        { value: "segments", label: "Segmentli", pro: true },
        { value: "neon", label: "Neon çizgi", pro: true },
        { value: "corner", label: "Parantez", pro: true },
      ],
    },
    {
      key: "thickness",
      label: "Çubuk kalınlığı",
      type: "number",
      default: 24,
      min: 4,
      max: 80,
      step: 1,
      unit: "px",
    },
    {
      key: "height",
      label: "Çubuk yüksekliği",
      type: "number",
      default: 180,
      min: 40,
      max: 800,
      step: 10,
      unit: "px",
    },
    {
      key: "gap",
      label: "Çubuklar arası mesafe",
      type: "number",
      default: 600,
      min: 40,
      max: 3000,
      step: 10,
      unit: "px",
      hint: "İki çubuğun iç kenarları arasındaki boşluk.",
    },
    {
      key: "onlyAlongside",
      label: "Sadece yanında araç varken göster",
      type: "boolean",
      default: true,
    },
    {
      key: "guides",
      label: "Çubukları silik kılavuz olarak hep göster",
      type: "boolean",
      default: false,
      hint: "Yanında kimse yokken de iki çubuk soluk biçimde görünür.",
    },
    {
      key: "showMarker",
      label: "Araç işaretini göster",
      type: "boolean",
      default: true,
      hint: "Yandaki aracın çubuk boyunca konumu: altta arkanda, üstte önünde.",
    },
    {
      key: "flip",
      label: "Yönü ters çevir",
      type: "boolean",
      default: false,
      hint: "Açıkken işaret üstte arkanda, altta önünde olan aracı gösterir.",
    },
    {
      key: "showDistance",
      label: "Mesafe yaz",
      type: "boolean",
      default: false,
    },
    {
      key: "range",
      label: "Çubuğun gösterdiği mesafe (ön/arka)",
      type: "number",
      default: 7,
      min: 4,
      max: 20,
      step: 1,
      unit: "m",
    },
    {
      key: "dangerDist",
      label: "Tehlikeli yakınlık",
      type: "number",
      default: 2,
      min: 0,
      max: 5,
      step: 0.5,
      unit: "m",
      hint: "Yandaki araç boyuna bu kadar yakınsa (neredeyse tam yan yana) çubuk tehlike rengine döner. 0: kapalı.",
    },
    {
      key: "colorCar",
      label: "Yanda araç rengi",
      type: "color",
      default: "#ff8a2a",
      group: "Renkler",
    },
    {
      key: "colorTwo",
      label: "İki yanda / iki araç rengi",
      type: "color",
      default: "#ffd21f",
      group: "Renkler",
    },
    {
      key: "colorDanger",
      label: "Tehlikeli yakınlık rengi",
      type: "color",
      default: "#ff2d3d",
      group: "Renkler",
    },
    {
      key: "colorClear",
      label: "Boş (kılavuz) rengi",
      type: "color",
      default: "#9aa3ad",
      group: "Renkler",
      resetKeys: ["colorCar", "colorTwo", "colorDanger", "colorClear"],
      resetLabel: "Renkleri sıfırla",
    },
    {
      key: "barOpacity",
      label: "Çubuk opaklığı",
      type: "number",
      default: 90,
      min: 20,
      max: 100,
      step: 5,
      unit: "%",
      group: "Efektler",
    },
    {
      key: "glow",
      label: "Parlama",
      type: "boolean",
      default: true,
      group: "Efektler",
    },
    {
      key: "pulse",
      label: "Tehlikede nabız gibi at",
      type: "boolean",
      default: true,
      group: "Efektler",
      hint: "Araç tehlikeli yakınlıktayken ya da iki yanında birden araç varken çubuklar hafifçe yanıp söner.",
    },
    {
      key: "fadeMs",
      label: "Belirme / kaybolma süresi",
      type: "number",
      default: 160,
      min: 0,
      max: 1000,
      step: 20,
      unit: "ms",
      group: "Efektler",
    },
    {
      key: "onlyOnTrack",
      label: "Sadece pistteyken göster",
      type: "boolean",
      default: true,
    },
    {
      key: "minSpeed",
      label: "En düşük hız",
      type: "number",
      default: 0,
      min: 0,
      max: 120,
      step: 5,
      unit: "km/s",
      hint: "Bu hızın altında (ör. pit yolunda) çubuklar gizlenir. 0: kapalı.",
    },
    {
      key: "hz",
      label: "Güncelleme sıklığı",
      type: "number",
      default: 30,
      min: 10,
      max: 60,
      step: 10,
      unit: "Hz",
    },
  ],
});
