import { defineOverlay } from "@/sdk/overlay";

export default defineOverlay({
  id: "goalbar",
  name: "Hedef Çubuğu",
  description:
    "Yayıncılar için hedef ilerleme çubuğu: elle sayaç ya da canlı sohbet uyarılarından (takipçi, abone / üye, bağış) kendiliğinden sayım. Başlık, hedef, yüzde ve istersen “son destekçi” satırı.",
  category: "stream",
  topics: [
    { name: "livechat", hz: 2 },
    { name: "status", hz: 1 },
  ],
  size: { w: 420, h: 70 },
  defaultPosition: { x: 60, y: 60 },
  defaultEnabled: false,
  defaultAlwaysShow: true,
  settings: [
    {
      key: "design",
      label: "Tasarım",
      type: "select",
      default: "slim",
      options: [
        { value: "slim", label: "İnce çubuk" },
        { value: "pill", label: "İkonlu hap" },
        { value: "milestone", label: "Büyük hedef panosu", pro: true },
      ],
    },
    { key: "title", label: "Başlık", type: "text", default: "Takipçi hedefi", placeholder: "Takipçi hedefi" },
    {
      key: "source",
      label: "Kaynak",
      type: "select",
      default: "manual",
      options: [
        { value: "manual", label: "Elle sayaç" },
        { value: "follower", label: "Yeni takipçiler (canlı sohbet uyarıları)" },
        { value: "sub", label: "Yeni aboneler / üyeler" },
        { value: "donation", label: "Bağış sayısı" },
        { value: "donationSum", label: "Bağış tutarı (toplam)" },
        { value: "all", label: "Tüm destekler (takipçi + abone + bağış)" },
      ],
      hint: "Uyarı kaynakları Canlı Sohbet çalışırken sayılır (Streamlabs ve platform uyarıları). Bağış tutarında farklı para birimleri çevrilmeden toplanır; bits tutara katılmaz.",
    },
    { key: "target", label: "Hedef", type: "text", default: "100", placeholder: "100" },
    { key: "base", label: "Başlangıç değeri", type: "text", default: "0", placeholder: "0", hint: "Elle sayaçta mevcut değer; uyarı kaynaklarında sayımın üstüne eklenen başlangıç (ör. şu anki takipçi sayın)." },
    { key: "adjust", label: "Elle ekle / çıkar", type: "number", default: 0, min: -9999, max: 9999, step: 1, ui: "stepper", hint: "− / + ile sayacı bir bir değiştir." },
    {
      key: "resetSeq",
      label: "Sayımı sıfırla (+ ile yeni dönem)",
      type: "number",
      default: 0,
      min: 0,
      max: 9999,
      step: 1,
      ui: "stepper",
      showIf: { key: "source", not: ["manual"] },
      hint: "Sayı her değiştiğinde uyarı sayımı sıfırdan başlar. Sayım, overlay'in çalıştığı yerde (uygulama / OBS tarayıcı kaynağı) tutulur.",
    },
    { key: "unit", label: "Birim (ör. ₺)", type: "text", default: "", placeholder: "₺", group: "İçerik" },
    { key: "showNumbers", label: "Sayıları göster (mevcut / hedef)", type: "boolean", default: true, group: "İçerik" },
    { key: "showPercent", label: "Yüzdeyi göster", type: "boolean", default: true, group: "İçerik" },
    { key: "showLast", label: "Son destekçiyi göster", type: "boolean", default: true, group: "İçerik", showIf: { key: "source", not: ["manual"] } },
    { key: "doneText", label: "Hedefe ulaşınca yazı", type: "text", default: "", placeholder: "HEDEFE ULAŞILDI!", group: "İçerik" },
    { key: "barColor", label: "Çubuk rengi", type: "color", default: "#ff8a2a", group: "Görünüm" },
    { key: "doneColor", label: "Hedefe ulaşınca renk", type: "color", default: "#33d17a", group: "Görünüm", resetKeys: ["barColor", "doneColor"], resetLabel: "Renkleri sıfırla" },
    { key: "width", label: "Genişlik", type: "number", default: 420, min: 180, max: 1200, step: 10, unit: "px", group: "Görünüm" },
    { key: "fontSize", label: "Yazı boyutu", type: "number", default: 15, min: 10, max: 36, step: 1, unit: "px", group: "Görünüm" },
  ],
});
