import { defineOverlay } from "@/sdk/overlay";

export default defineOverlay({
  id: "crewcall",
  name: "Ekip Çağrısı",
  description:
    "Ekibin Ekip odasından bir çağrı ya da mesaj gönderdiğinde veya bir pit komutu uygulandığında ekranın ortasında büyük, gözden kaçmayan bir duyuru gösterir. \"Bu tur pit\", \"Push\", \"Yakıt tasarrufu\" ve \"Arkandan hızlı araç\" gibi hazır çağrılar kendi rengi ve simgesiyle çıkar.",
  category: "race",
  topics: [],
  size: { w: 640, h: 120 },
  defaultPosition: { x: 640, y: 240 },
  defaultCenter: true,
  defaultEnabled: false,
  settings: [
    { key: "width", label: "Genişlik", type: "number", default: 640, min: 320, max: 1400, step: 10, unit: "px" },
    { key: "fontSize", label: "Yazı boyutu", type: "number", default: 34, min: 16, max: 80, step: 1, unit: "px" },
    { key: "duration", label: "Ekranda kalma süresi", type: "number", default: 8, min: 2, max: 60, step: 1, unit: "sn", ui: "stepper" },
    {
      key: "anim",
      label: "Dikkat çekme animasyonu",
      type: "select",
      default: "pulse",
      options: [
        { value: "pulse", label: "Nabız" },
        { value: "flash", label: "Yanıp sönme" },
        { value: "slide", label: "Yukarıdan kayarak" },
        { value: "none", label: "Yok" },
      ],
      hint: "Animasyon duyuru çıkarken birkaç kez oynar, sonra durur.",
    },
    { key: "upper", label: "BÜYÜK HARF", type: "boolean", default: true },
    { key: "showSender", label: "Göndereni göster", type: "boolean", default: true },
    { key: "showIcon", label: "Çağrı simgesi", type: "boolean", default: true },
    { key: "bgOpacity", label: "Arka plan opaklığı", type: "number", default: 92, min: 30, max: 100, step: 1, unit: "%" },
    { key: "showMessages", label: "Ekip odası mesajları", type: "boolean", default: true, group: "Kaynak" },
    {
      key: "quickOnly",
      label: "Yalnızca hazır çağrılar",
      type: "boolean",
      default: false,
      group: "Kaynak",
      showIf: { key: "showMessages", is: [true] },
      hint: "Açıkken sıradan sohbet mesajları ortada gösterilmez; yalnızca pit, push, yakıt tasarrufu, hızlı araç ve spotter çağrıları çıkar.",
    },
    { key: "showCommands", label: "Uygulanan pit komutları", type: "boolean", default: true, group: "Kaynak", hint: "Ekibin uzaktan yaptığı pit ayarı (yakıt, lastik, hızlı tamir...) uygulanınca duyurulur." },
    { key: "sound", label: "Uyarı sesi (bip)", type: "boolean", default: true, group: "Ses" },
    { key: "volume", label: "Ses düzeyi", type: "number", default: 50, min: 5, max: 100, step: 5, unit: "%", group: "Ses", showIf: { key: "sound", is: [true] } },
    { key: "color", label: "Genel mesaj rengi", type: "color", default: "#ff8a2a", group: "Renkler" },
    { key: "pitColor", label: "Pit çağrısı rengi", type: "color", default: "#ffcc33", group: "Renkler" },
    { key: "pushColor", label: "Push rengi", type: "color", default: "#33d17a", group: "Renkler" },
    { key: "fuelColor", label: "Yakıt tasarrufu rengi", type: "color", default: "#4aa8ff", group: "Renkler" },
    { key: "fastColor", label: "Hızlı araç rengi", type: "color", default: "#3b6cff", group: "Renkler", resetKeys: ["color", "pitColor", "pushColor", "fuelColor", "fastColor"], resetLabel: "Renkleri sıfırla" },
  ],
});
