import { defineOverlay } from "@/sdk/overlay";

export default defineOverlay({
  id: "brakepoint",
  name: "Fren ve Vites İşareti",
  description:
    "En iyi geçerli turundaki fren noktalarını referans alır: sıradaki fren noktasına geri sayım, virajın vitesi ve son virajda referansa göre kaç metre erken ya da geç frenlediğin.",
  category: "driving",
  // Tekrar ekranında çalışmaz (sürüş verisi yalnızca kendin sürerken gelir)
  replay: false,
  topics: [{ name: "brakepoint", hz: 30 }],
  size: { w: 320, h: 92 },
  defaultPosition: { x: 800, y: 620 },
  defaultEnabled: false,
  settings: [
    {
      key: "design",
      label: "Tasarım",
      type: "select",
      default: "bar",
      options: [
        { value: "bar", label: "Yatay geri sayım çubuğu" },
        { value: "sign", label: "Parlayan FREN tabelası" },
        { value: "neon", label: "Neon tabela" },
        { value: "hazard", label: "Uyarı şeridi" },
        { value: "alert", label: "İkaz üçgeni" },
        { value: "boards", label: "Mesafe levhaları", pro: true },
        { value: "ring", label: "Geri sayım halkası", pro: true },
      ],
      hint: "Yatay çubuk: mesafe işaretli geri sayım. Parlayan tabela: yaklaştıkça dolan, fren noktasında kırmızı parlayan büyük FREN yazısı. Neon: içi boş, parlayan tüp yazı. Uyarı şeridi: çapraz çizgili ikaz bandı. İkaz üçgeni: ünlemli üçgenle birlikte. Mesafe levhaları: pist kenarındaki levhalar gibi sırayla yanar. Halka: ortasında virajın vitesi olan geri sayım.",
      proHint: "Mesafe levhaları ve halka tasarımları PRO üyelere özel.",
    },
    {
      key: "source",
      label: "Fren noktaları neye göre",
      type: "select",
      default: "best",
      options: [
        { value: "best", label: "Tüm zamanlardaki kendi rekorum" },
        { value: "session", label: "Bu oturumdaki en iyi turum" },
        { value: "community", label: "Topluluk rekoru (telemetri kayıtları)" },
      ],
      hint: "Kendi rekorum: bu pist ve araçta bugüne kadarki en iyi temiz turun (bilgisayarında saklanır). Bu oturum: yalnızca bu oturumda attığın en iyi temiz tur. Topluluk rekoru: Telemetri sayfasındaki sıralamada bu pist ve araç için izi paylaşılmış en hızlı turun fren ve gaz kesme noktaları; hesabınla giriş yapmış olman gerekir.",
    },
    {
      key: "range",
      label: "Geri sayım başlangıcı",
      type: "number",
      default: 150,
      min: 50,
      max: 400,
      step: 10,
      unit: "m",
      hint: "Fren noktasına bu mesafe kala geri sayım başlar. Çubuktaki işaretler 50 metrede bir konur.",
    },
    {
      key: "lead",
      label: "Erken uyarı payı",
      type: "number",
      default: 0.15,
      min: 0,
      max: 1,
      step: 0.05,
      unit: "sn",
      hint: "ŞİMDİ uyarısı, o anki hızınla bu süre kadar önce yanar (tepki süresi payı). 0: tam referans noktasında.",
    },
    { key: "showGear", label: "Virajın vitesini göster", type: "boolean", default: true, hint: "Referans turda o virajda kullandığın en düşük vites." },
    { key: "showSpeed", label: "Virajın en düşük hızını göster", type: "boolean", default: false },
    { key: "showLift", label: "Gaz kesme noktalarını da işaretle", type: "boolean", default: true, hint: "Fren yapmadan sadece gazı kestiğin virajlar da geri sayımla gösterilir." },
    { key: "showDiff", label: "Son virajdaki fark (± metre)", type: "boolean", default: true, hint: "Referans tura göre kaç metre erken ya da geç frenlediğin." },
    { key: "diffHold", label: "Farkın ekranda kalma süresi", type: "number", default: 6, min: 2, max: 30, step: 1, unit: "sn", showIf: { key: "showDiff", is: [true] } },
    { key: "showMini", label: "Tur şeridi (fren noktaları)", type: "boolean", default: true, showIf: { key: "design", is: ["bar"] }, hint: "Turun tamamını ince bir şeritte, fren noktaları ve konumunla gösterir." },
    { key: "hideIdle", label: "Fren noktası uzaktayken gizle", type: "boolean", default: false, hint: "Geri sayım başlayana kadar gösterge ekranda yer kaplamaz." },
    { key: "hidePits", label: "Pitte gizle", type: "boolean", default: true },

    { key: "colFar", label: "Uzak rengi", type: "color", default: "#4aa8ff", group: "Renkler" },
    { key: "colNear", label: "Yaklaşıyor rengi", type: "color", default: "#ffcc33", group: "Renkler" },
    { key: "colNow", label: "ŞİMDİ rengi", type: "color", default: "#ff4d4f", group: "Renkler" },

    { key: "fontSize", label: "Yazı boyutu", type: "number", default: 14, min: 10, max: 30, step: 1, unit: "px", group: "Görünüm", hint: "Bütün gösterge yazı boyutuyla birlikte büyür ve küçülür." },
    { key: "width", label: "Genişlik", type: "number", default: 320, min: 200, max: 700, step: 10, unit: "px", group: "Görünüm", showIf: { key: "design", is: ["bar", "sign", "neon", "hazard", "alert", "boards"] } },
  ],
});
