import { defineOverlay } from "@/sdk/overlay";
import { METRICS } from "./metrics";

export default defineOverlay({
  id: "dataframe",
  name: "Veri Kutusu",
  description: "Seçtiğin tek bir değeri büyük gösteren kutu: hız, vites, yakıt, delta, pozisyon, tur, sıcaklık, BB ve daha fazlası.",
  category: "info",
  // Tekrar ekranında çalışmaz (sürüş verisi yalnızca kendin sürerken gelir)
  replay: false,
  topics: [
    { name: "telemetry", hz: 10 },
    { name: "session", hz: 2 },
    { name: "fuel", hz: 2 },
    { name: "delta", hz: 10 },
  ],
  size: { w: 150, h: 70 },
  defaultPosition: { x: 1200, y: 900 },
  defaultEnabled: false,
  multiInstance: true,
  settings: [
    {
      key: "metric",
      label: "Gösterilecek değer",
      type: "select",
      default: "speed",
      options: METRICS.map((m) => ({ value: m.id, label: m.label })),
    },
    { key: "title", label: "Başlığı göster", type: "boolean", default: true },
    { key: "customTitle", label: "Özel başlık", type: "text", default: "", placeholder: "Boşsa değerin adı yazılır", showIf: { key: "title", is: [true] } },
    { key: "showUnit", label: "Birimi göster", type: "boolean", default: true, hint: "Değerin yanındaki km/h, L, tur gibi birim yazısı." },
    { key: "width", label: "Genişlik", type: "number", default: 150, min: 60, max: 400, step: 10, unit: "px" },
    { key: "big", label: "Değer boyutu", type: "number", default: 26, min: 12, max: 96, step: 2, unit: "px" },
    {
      key: "shape",
      label: "Şekil",
      type: "select",
      default: "rounded",
      group: "Şekil",
      options: [
        { value: "rounded", label: "Yuvarlak köşeli (tema)" },
        { value: "square", label: "Köşeli" },
        { value: "pill", label: "Hap" },
        { value: "circle", label: "Daire" },
        { value: "cut", label: "Kesik köşeli" },
        { value: "slant", label: "Eğik (paralelkenar)" },
        { value: "underline", label: "Alt çizgili (kutusuz)" },
        { value: "plain", label: "Yalnızca yazı (kutusuz)" },
      ],
      hint: "Daire şeklinde kutunun çapı Genişlik ayarıdır.",
    },
    {
      key: "accentBar",
      label: "Vurgu şeridi",
      type: "select",
      default: "none",
      group: "Şekil",
      showIf: { key: "shape", not: ["circle", "underline", "plain"] },
      options: [
        { value: "none", label: "Yok" },
        { value: "left", label: "Solda" },
        { value: "right", label: "Sağda" },
        { value: "top", label: "Üstte" },
        { value: "bottom", label: "Altta" },
      ],
    },
    { key: "pad", label: "İç boşluk", type: "number", default: 100, min: 40, max: 300, step: 10, unit: "%", group: "Şekil", showIf: { key: "shape", not: ["circle"] } },
    {
      key: "titlePos",
      label: "Başlığın yeri",
      type: "select",
      default: "top",
      group: "Yazı",
      showIf: { key: "title", is: [true] },
      options: [
        { value: "top", label: "Üstte" },
        { value: "bottom", label: "Altta" },
        { value: "left", label: "Solda (tek satır)" },
      ],
    },
    {
      key: "align",
      label: "Hizalama",
      type: "select",
      default: "center",
      group: "Yazı",
      options: [
        { value: "center", label: "Ortala" },
        { value: "left", label: "Sola" },
        { value: "right", label: "Sağa" },
      ],
    },
    { key: "titleSize", label: "Başlık boyutu", type: "number", default: 100, min: 60, max: 220, step: 10, unit: "%", group: "Yazı", showIf: { key: "title", is: [true] } },
    { key: "toneColors", label: "Değere göre renk", type: "boolean", default: true, group: "Renkler", hint: "Delta gibi değerlerde iyi / kötü durumda yeşil / kırmızı yazar. Kapalıyken hep değer rengiyle yazılır." },
    { key: "glow", label: "Yazı parlaması", type: "boolean", default: false, group: "Renkler", hint: "Değerin çevresine vurgu renginde hafif bir ışık ekler." },
    { key: "customColors", label: "Özel renkler", type: "boolean", default: false, group: "Renkler", hint: "Kapalıyken kutu temanın (ya da bu overlay'in Görünüm ayarının) renklerini kullanır." },
    { key: "bg", label: "Arka plan rengi", type: "color", default: "#0c0e13", group: "Renkler", showIf: { key: "customColors", is: [true] } },
    { key: "bgAlpha", label: "Arka plan opaklığı", type: "number", default: 86, min: 0, max: 100, step: 5, unit: "%", group: "Renkler", showIf: { key: "customColors", is: [true] } },
    { key: "valueColor", label: "Değer rengi", type: "color", default: "#f2f4f8", group: "Renkler", showIf: { key: "customColors", is: [true] } },
    { key: "titleColor", label: "Başlık ve birim rengi", type: "color", default: "#9aa3b2", group: "Renkler", showIf: { key: "customColors", is: [true] } },
    { key: "accentColor", label: "Vurgu rengi", type: "color", default: "#ff8a2a", group: "Renkler", showIf: { key: "customColors", is: [true] }, hint: "Vurgu şeridi, alt çizgi ve yazı parlamasında kullanılır." },
    { key: "borderColor", label: "Kenarlık rengi", type: "color", default: "#2a2f3a", group: "Renkler", showIf: { key: "customColors", is: [true] } },
    { key: "borderW", label: "Kenarlık kalınlığı", type: "number", default: 1, min: 0, max: 6, step: 1, unit: "px", group: "Renkler", showIf: { key: "customColors", is: [true] } },
  ],
});
