import { defineOverlay } from "@/sdk/overlay";
import { FONT_OPTIONS } from "./opts";

const G_LOOK = "Görünüm";
const G_CONTENT = "İçerik";
const G_BAR = "İzleyici çubuğu";

export default defineOverlay({
  id: "livechat",
  name: "Canlı Sohbet",
  description:
    "YouTube, Twitch ve Kick sohbetini tek akışta gösterir (emote'lar, rozetler, Super Chat, abonelik ve raid uyarıları, izleyici sayıları). Kanallar Canlı Sohbet sayfasından eklenir; OBS'te de kullanılabilir.",
  category: "stream",
  topics: [
    { name: "livechat", hz: 10 },
    { name: "livepoll", hz: 10 },
    { name: "captions", hz: 5 },
  ],
  size: { w: 480, h: 600 },
  defaultPosition: { x: 20, y: 420 },
  defaultEnabled: false,
  defaultAlwaysShow: true,
  settings: [
    {
      key: "always",
      label: "Sürekli göster",
      type: "boolean",
      default: true,
      hint: "Oyunda / seansta değilken de (oyun kapalı, tekrar izlerken, pist dışında) görünür.",
      group: G_LOOK,
    },
    {
      key: "onlyLive",
      label: "Yalnızca yayın canlıyken göster",
      type: "boolean",
      default: true,
      hint: "Açık: sohbet çalışsa da yayın canlı değilken overlay görünmez (mesaj gelmeye başlayınca canlı sayılır). Kapalı: sohbet çalıştığı sürece mesajlar gösterilir.",
      group: G_LOOK,
    },
    { key: "width", label: "Genişlik", type: "number", default: 480, min: 220, max: 900, step: 10, unit: "px", group: G_LOOK },
    {
      key: "height",
      label: "Yükseklik",
      type: "number",
      default: 600,
      min: 120,
      max: 1400,
      step: 10,
      unit: "px",
      hint: "Mesajlar bu alanın alt kenarından başlar ve yukarı doğru birikir; sığmayan eski mesajlar üstten kaybolur.",
      group: G_LOOK,
    },
    { key: "maxMessages", label: "En fazla mesaj", type: "number", default: 10, min: 3, max: 60, step: 1, group: G_LOOK },
    {
      key: "fade",
      label: "Mesaj ekranda kalma süresi",
      type: "number",
      default: 180,
      min: 0,
      max: 600,
      step: 10,
      unit: "sn",
      hint: "0 = mesajlar kalır.",
      group: G_LOOK,
    },
    {
      key: "newestTop",
      label: "Yeni mesaj üstte",
      type: "boolean",
      default: false,
      hint: "Kapalı (önerilen): yeni mesaj her zaman en altta görünür, eskiler yukarı kayar.",
      group: G_LOOK,
    },
    { key: "font", label: "Yazı tipi", type: "select", default: "", options: FONT_OPTIONS, group: G_LOOK },
    { key: "fontSize", label: "Yazı boyutu", type: "number", default: 16, min: 10, max: 48, step: 1, unit: "px", group: G_LOOK },
    { key: "emoteSize", label: "Emote boyutu", type: "number", default: 24, min: 14, max: 72, step: 2, unit: "px", group: G_LOOK },
    { key: "usernameColor", label: "Kullanıcı adı rengi", type: "color", default: "#00FF00", group: G_LOOK },
    {
      key: "userColors",
      label: "Kullanıcının kendi rengini kullan (Twitch/Kick)",
      type: "boolean",
      default: false,
      group: G_LOOK,
    },
    { key: "messageColor", label: "Mesaj rengi", type: "color", default: "#FFFFFF", group: G_LOOK },
    { key: "bubbles", label: "Mesaj balonları", type: "boolean", default: true, group: G_LOOK },
    { key: "bgColor", label: "Arka plan rengi", type: "color", default: "#000000", group: G_LOOK },
    { key: "bgOpacity", label: "Arka plan opaklığı", type: "number", default: 55, min: 0, max: 100, step: 5, unit: "%", group: G_LOOK },
    { key: "showIcons", label: "Platform simgeleri", type: "boolean", default: true, group: G_LOOK },
    { key: "youtubeColor", label: "YouTube etiket rengi", type: "color", default: "#ff6b6b", group: G_LOOK },
    { key: "twitchColor", label: "Twitch etiket rengi", type: "color", default: "#b28cff", group: G_LOOK },
    { key: "kickColor", label: "Kick etiket rengi", type: "color", default: "#53fc18", group: G_LOOK },
    {
      key: "channelTag",
      label: "[kanal] etiketi",
      type: "select",
      default: "auto",
      options: [
        { value: "auto", label: "Kanal ayarına göre" },
        { value: "always", label: "Her zaman" },
        { value: "never", label: "Hiçbir zaman" },
      ],
      group: G_LOOK,
    },
    { key: "showBadges", label: "Rozetler (yayıncı, mod, abone, VIP, üye)", type: "boolean", default: true, group: G_LOOK },
    { key: "nameMax", label: "Ad kısaltma", type: "number", default: 16, min: 0, max: 40, step: 1, hint: "0 = kısaltma yok.", group: G_LOOK },
    {
      key: "alertStyle",
      label: "Uyarılar (abone, raid, bağış, Super Chat)",
      type: "select",
      default: "box",
      options: [
        { value: "box", label: "Renkli kutu" },
        { value: "line", label: "Sade satır" },
        { value: "off", label: "Gösterme" },
      ],
      group: G_CONTENT,
    },
    {
      key: "deleted",
      label: "Silinen mesajlar",
      type: "select",
      default: "mark",
      options: [
        { value: "mark", label: "\"mesaj silindi\" yazıp soldur" },
        { value: "hide", label: "Hemen kaldır" },
      ],
      group: G_CONTENT,
    },
    { key: "hideCommands", label: "! komutlarını gizle", type: "boolean", default: false, group: G_CONTENT },
    { key: "hideBots", label: "Gizlenecek botlar (virgülle)", type: "text", default: "nightbot,streamelements,streamlabs,moobot,fossabot", group: G_CONTENT },
    { key: "showReplies", label: "Yanıtlanan mesajı göster", type: "boolean", default: true, group: G_CONTENT },
    { key: "showPoll", label: "Anketi sohbetin üstünde göster", type: "boolean", default: false, group: G_CONTENT },
    { key: "showCaptions", label: "Altyazıyı sohbetin üstünde göster", type: "boolean", default: false, group: G_CONTENT },
    {
      key: "viewerBar",
      label: "İzleyici çubuğu",
      type: "select",
      default: "normal",
      options: [
        { value: "off", label: "Kapalı" },
        { value: "small", label: "Küçük" },
        { value: "normal", label: "Normal" },
        { value: "large", label: "Büyük" },
      ],
      group: G_BAR,
    },
    {
      key: "viewerMode",
      label: "Gösterim",
      type: "select",
      default: "detail",
      options: [
        { value: "detail", label: "Platform başına + toplam" },
        { value: "total", label: "Sadece toplam" },
      ],
      showIf: { key: "viewerBar", not: ["off"] },
      group: G_BAR,
    },
    { key: "showClock", label: "Saat", type: "boolean", default: true, showIf: { key: "viewerBar", not: ["off"] }, group: G_BAR },
  ],
});
