import { defineOverlay } from "@/sdk/overlay";

export default defineOverlay({
  id: "gforce",
  name: "G-Force",
  description: "Yanal ve boyuna g kuvveti: iz bırakan g-çemberi, tepe değer işaretleri, çubuklar, sayısal görünüm ve sürtünme çemberi.",
  category: "driving",
  topics: [{ name: "inputs", hz: 60 }],
  size: { w: 210, h: 250 },
  defaultPosition: { x: 1180, y: 780 },
  defaultEnabled: false,
  settings: [
    {
      key: "design",
      label: "Tasarım",
      type: "select",
      default: "circle",
      options: [
        { value: "circle", label: "Klasik g-çemberi" },
        { value: "bars", label: "Çubuklar (yanal / boyuna)" },
        { value: "numeric", label: "Sayısal (minimal)" },
        { value: "friction", label: "Sürtünme çemberi" },
      ],
      hint: "G-çemberi: nokta, iz ve tepe işaretleri. Çubuklar: yanal ve boyuna ayrı çubuklar. Sayısal: sadece rakamlar. Sürtünme çemberi: geçmiş noktalar yavaşça solar, kullandığın tutunma sınırı çizgiyle belirir.",
    },
    { key: "maxG", label: "En yüksek g (ölçek)", type: "number", default: 3, min: 1, max: 6, step: 0.5, unit: "g", hint: "Göstergenin dış kenarına karşılık gelen g değeri. Formula araçlarında 5–6, GT araçlarında 2,5–3 uygundur." },
    {
      key: "trail",
      label: "İz uzunluğu",
      type: "number",
      default: 2,
      min: 0,
      max: 12,
      step: 0.5,
      unit: "sn",
      showIf: { key: "design", is: ["circle", "friction"] },
      hint: "Noktanın arkasında bıraktığı izin süresi. 0: iz yok.",
    },
    { key: "smoothing", label: "Yumuşatma", type: "number", default: 40, min: 0, max: 90, step: 5, unit: "%", hint: "Titreşimi azaltır; yüksek değerlerde gösterge biraz gecikir." },
    { key: "showPeaks", label: "Tepe değerleri göster", type: "boolean", default: true },
    {
      key: "peakHold",
      label: "Tepe değeri tutma süresi",
      type: "number",
      default: 10,
      min: 2,
      max: 120,
      step: 1,
      unit: "sn",
      showIf: { key: "showPeaks", is: [true] },
    },
    { key: "showNumbers", label: "Sayıları göster", type: "boolean", default: true, showIf: { key: "design", not: ["numeric"] } },
    {
      key: "flipLong",
      label: "Fren aşağıda olsun",
      type: "boolean",
      default: false,
      group: "Yön",
      hint: "Kapalıyken frende nokta yukarı, hızlanırken aşağı gider (sürücünün hissettiği yön).",
    },
    {
      key: "flipLat",
      label: "Yatay yönü ters çevir",
      type: "boolean",
      default: false,
      group: "Yön",
      hint: "Kapalıyken sağ virajda nokta sola gider (sürücünün savrulduğu yön). Açınca viraj yönüne gider.",
    },
    { key: "dotColor", label: "Nokta ve iz rengi", type: "color", default: "#ff8a2a", group: "Renkler" },
    { key: "peakColor", label: "Tepe işareti rengi", type: "color", default: "#b76cff", group: "Renkler" },
    { key: "hz", label: "Güncelleme sıklığı", type: "number", default: 60, min: 20, max: 60, step: 10, unit: "Hz" },
  ],
});
