import { defineOverlay } from "@/sdk/overlay";
import { meMarkerFields } from "./marker";

export default defineOverlay({
  id: "trackmap",
  name: "Pist Haritası",
  description:
    "Tüm pist ve üzerindeki araçlar; sınıf renkleri, numaralar, senin aracın vurgulu. Pist şekli ilk temiz turunda otomatik kaydedilir.",
  category: "race",
  topics: [{ name: "map", hz: 10 }],
  size: { w: 360, h: 280 },
  defaultPosition: { x: 1500, y: 240 },
  defaultEnabled: false,
  settings: [
    {
      key: "label",
      label: "Araç üzerindeki yazı",
      type: "select",
      default: "number",
      options: [
        { value: "number", label: "Araç numarası" },
        { value: "pos", label: "Sınıf pozisyonu" },
        { value: "none", label: "Yok" },
      ],
    },
    { key: "width", label: "Genişlik", type: "number", default: 360, min: 160, max: 1200, step: 10, unit: "px" },
    { key: "height", label: "Yükseklik", type: "number", default: 280, min: 120, max: 1000, step: 10, unit: "px" },
    { key: "carSize", label: "Araç işareti boyutu", type: "number", default: 11, min: 5, max: 20, step: 1, unit: "px" },
    { key: "lineWidth", label: "Pist çizgi kalınlığı", type: "number", default: 5, min: 2, max: 14, step: 1, unit: "px" },
    {
      key: "rotate",
      label: "Döndür",
      type: "select",
      default: "0",
      options: [
        { value: "auto", label: "Otomatik (start çizgisi altta)" },
        { value: "0", label: "0°" },
        { value: "90", label: "90°" },
        { value: "180", label: "180°" },
        { value: "270", label: "270°" },
      ],
    },
    { key: "mirror", label: "Aynala (harita ters görünüyorsa)", type: "boolean", default: false },
    { key: "fill", label: "Pist içini doldur", type: "boolean", default: false },
    { key: "rotateFine", label: "Ek döndürme açısı", type: "number", default: 0, min: 0, max: 355, step: 5, unit: "°", group: "Pist görünümü" },
    {
      key: "fillOpacity",
      label: "Dolgu opaklığı",
      type: "number",
      default: 100,
      min: 0,
      max: 100,
      step: 5,
      unit: "%",
      group: "Pist görünümü",
      showIf: { key: "fill", is: [true] },
    },
    { key: "outline", label: "Pist kenar çizgisi", type: "boolean", default: true, group: "Pist görünümü" },
    {
      key: "outlineWidth",
      label: "Kenar çizgisi kalınlığı",
      type: "number",
      default: 2,
      min: 1,
      max: 8,
      step: 1,
      unit: "px",
      group: "Pist görünümü",
      showIf: { key: "outline", is: [true] },
    },
    { key: "sfLine", label: "Başlangıç / bitiş çizgisi", type: "boolean", default: true, group: "Pist görünümü" },
    {
      key: "customColors",
      label: "Özel renkler kullan",
      type: "boolean",
      default: false,
      group: "Pist görünümü",
      hint: "Kapalıyken pist, kenar çizgisi ve dolgu temanın renklerini kullanır.",
    },
    { key: "trackColor", label: "Pist (yol) rengi", type: "color", default: "#ffffff", group: "Pist görünümü", showIf: { key: "customColors", is: [true] } },
    { key: "outlineColor", label: "Kenar çizgisi rengi", type: "color", default: "#11131a", group: "Pist görünümü", showIf: { key: "customColors", is: [true] } },
    { key: "fillColor", label: "Dolgu rengi", type: "color", default: "#0c0e13", group: "Pist görünümü", showIf: { key: "customColors", is: [true] } },
    { key: "sfColor", label: "Başlangıç / bitiş çizgisi rengi", type: "color", default: "#ffffff", group: "Pist görünümü", showIf: { key: "customColors", is: [true] } },
    {
      key: "pitLane",
      label: "Pit yolunu göster",
      type: "boolean",
      default: true,
      group: "Pit yolu",
      hint: "Pit girişi ve çıkışı, araçlar pite girip çıktıkça otomatik öğrenilir ve pist başına saklanır. Henüz öğrenilmediyse pit yolu çizilmez.",
    },
    {
      key: "pitSide",
      label: "Pit tarafı",
      type: "select",
      default: "auto",
      group: "Pit yolu",
      showIf: { key: "pitLane", is: [true] },
      options: [
        { value: "auto", label: "Otomatik" },
        { value: "in", label: "Pistin içi" },
        { value: "out", label: "Pistin dışı" },
      ],
    },
    { key: "pitColor", label: "Pit yolu rengi", type: "color", default: "#ffb020", group: "Pit yolu", showIf: { key: "pitLane", is: [true] } },
    { key: "pitWidth", label: "Pit yolu kalınlığı", type: "number", default: 3, min: 1, max: 10, step: 1, unit: "px", group: "Pit yolu", showIf: { key: "pitLane", is: [true] } },
    { key: "pitOffset", label: "Pit yolunun pistten uzaklığı", type: "number", default: 10, min: 4, max: 40, step: 1, unit: "px", group: "Pit yolu", showIf: { key: "pitLane", is: [true] } },
    { key: "pitMarks", label: "Pit girişi / çıkışı işaretleri", type: "boolean", default: true, group: "Pit yolu", showIf: { key: "pitLane", is: [true] } },
    { key: "pitStall", label: "Pit kutumu göster", type: "boolean", default: true, group: "Pit yolu", showIf: { key: "pitLane", is: [true] } },
    { key: "pitCars", label: "Pitteki araçları pit yolunda çiz", type: "boolean", default: true, group: "Pit yolu", showIf: { key: "pitLane", is: [true] } },
    { key: "classColors", label: "Sınıf renklerini kullan", type: "boolean", default: true, group: "Araçlar" },
    { key: "carColor", label: "Araç rengi", type: "color", default: "#e03b3b", group: "Araçlar", showIf: { key: "classColors", is: [false] } },
    { key: "dimPit", label: "Pitteki araçları soluk göster", type: "boolean", default: true, group: "Araçlar" },
    ...meMarkerFields({ color: "#ff3b30", shape: "arrow" }),
    { key: "hz", label: "Güncelleme sıklığı", type: "number", default: 10, min: 2, max: 30, step: 1, unit: "Hz" },
  ],
});
